name: executing remote ssh commands using password
uses: appleboy/ssh-action@master
with:
  host: ${{ secrets.IBMISYS1 }}
  username: ${{ secrets.IBMIUSER }}
  password: ${{ secrets.IBMIPASSWORD }}
  port: 22
  # no inheriting env vars, must be passed through
envs: GIT_BRANCH  
 script: |
  echo Running on branch $GIT_BRANCH
  
